/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempakarsidat;

import Parameter.Alkalinitas;
import Parameter.Amonia;
import Parameter.DO;
import Parameter.Nitrit;
import Parameter.PH;
import Parameter.Suhu;
import Parameter.SurvivalRate;
import java.text.DecimalFormat;
/**
 *
 * @author Ardhipc
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        verify1 = new sistempakarsidat.verify();
        jFrame2 = new javax.swing.JFrame();
        fSuhu = new javax.swing.JTextField();
        fPh = new javax.swing.JTextField();
        fDo = new javax.swing.JTextField();
        fAmonia = new javax.swing.JTextField();
        fNitrit = new javax.swing.JTextField();
        fAlkali = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ex_alkali = new javax.swing.JLabel();
        ex_nitrit = new javax.swing.JLabel();
        ex_amonia = new javax.swing.JLabel();
        ex_do = new javax.swing.JLabel();
        ex_ph = new javax.swing.JLabel();
        ex_suhu = new javax.swing.JLabel();
        ex_judul = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        statusSR = new javax.swing.JLabel();
        nilaiSR = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fSuhu.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        fSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSuhuActionPerformed(evt);
            }
        });
        fSuhu.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fSuhuInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(fSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 63, -1));

        fPh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fPh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPhActionPerformed(evt);
            }
        });
        getContentPane().add(fPh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 63, -1));

        fDo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(fDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 63, -1));

        fAmonia.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(fAmonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 63, -1));

        fNitrit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(fNitrit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 63, -1));

        fAlkali.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(fAlkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 63, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Suhu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("PH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 40, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("DO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Amonia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Nitrit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Alkalinitas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel9.setText("Explanation");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));
        getContentPane().add(ex_alkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 300, 30));
        getContentPane().add(ex_nitrit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 300, 30));
        getContentPane().add(ex_amonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 300, 30));
        getContentPane().add(ex_do, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 300, 30));
        getContentPane().add(ex_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 300, 30));
        getContentPane().add(ex_suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 300, 30));
        getContentPane().add(ex_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 300, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 10, 430));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        statusSR.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        statusSR.setBorder(javax.swing.BorderFactory.createTitledBorder("Dengan Nilai"));

        nilaiSR.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        nilaiSR.setToolTipText("");
        nilaiSR.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(statusSR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(nilaiSR, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(nilaiSR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusSR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 300, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 360, 230));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("// 15-40");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 40, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("// 1-14");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 40, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("// 0-8");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setText("// 0-1");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setText("// 0-2");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 40, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel17.setText("// 40-220");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 60, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/ICON/HITUNG_ICON.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/ICON/BACK_ICON.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/ICON/REEST_ICON.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/PERHITUNGAN SURVIVAL RATE1.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fPhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fPhActionPerformed

    
        
    private void fSuhuInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fSuhuInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fSuhuInputMethodTextChanged

    private void fSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSuhuActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        Suhu.setSuhu(Double.parseDouble(fSuhu.getText()));
        Alkalinitas.setAlkalinitas(Double.parseDouble(fAlkali.getText()));
        Amonia.setAmonia(Double.parseDouble(fAmonia.getText()));
        DO.setDo(Double.parseDouble(fDo.getText()));
        Nitrit.setNitrit(Double.parseDouble(fNitrit.getText()));
        PH.setPh(Double.parseDouble(fPh.getText()));
        
        DecimalFormat df = new DecimalFormat("#########.###");
        Rule.compute_u();
        Rule.compute_z();
        statusSR.setText(df.format(Rule.cog())+"%");
        nilaiSR.setText(SurvivalRate.getStatus());
        ex_judul.setText("Air memiliki kondisi: \n");
        ex_suhu.setText("1. "+Suhu.getStatus());
        ex_ph.setText("2. "+PH.getStatus());
        ex_do.setText("3. "+DO.getStatus());
        ex_amonia.setText("4. "+Amonia.getStatus());
        ex_nitrit.setText("5. "+Nitrit.getStatus());
        ex_alkali.setText("6. "+Alkalinitas.getStatus());
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain().setVisible(true);
            }
        });
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ex_alkali;
    private javax.swing.JLabel ex_amonia;
    private javax.swing.JLabel ex_do;
    private javax.swing.JLabel ex_judul;
    private javax.swing.JLabel ex_nitrit;
    private javax.swing.JLabel ex_ph;
    private javax.swing.JLabel ex_suhu;
    private javax.swing.JTextField fAlkali;
    private javax.swing.JTextField fAmonia;
    private javax.swing.JTextField fDo;
    private javax.swing.JTextField fNitrit;
    private javax.swing.JTextField fPh;
    private javax.swing.JTextField fSuhu;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nilaiSR;
    private javax.swing.JLabel statusSR;
    private sistempakarsidat.verify verify1;
    // End of variables declaration//GEN-END:variables
}
